collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "experiences"
  - scope:
      path: ""
    values:
      layout: "default"