collections:
    projects:
        output: true
    experiences:

defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "projects"
    - scope:
          path: ""
      values:
          layout: "default"
