permalink: pretty
incremental: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true
  experiences:
    output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "404.html"
    values:
      permalink: "/404.html"

exclude:
  - api
  - pipelines
