permalink: pretty

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

collections:
    projects:
        output: true
    experiences:

defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "projects"
    - scope:
          path: ""
      values:
          layout: "default"
