services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    expose:
      - "8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/Containers/portfolio/dev:/usr/share/nginx/html/dev
      - ~/Containers/portfolio/prod:/usr/share/nginx/html/prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet
      - monitornet

  api:
    build:
      context: ../api
      dockerfile: ../pipelines/api.Dockerfile
    environment:
      - WAKATIME_API_KEY=${WAKATIME_API_KEY}
    expose:
      - "3000"
    networks:
      - webnet

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command: --nginx.scrape-uri=http://nginx:8081/nginx-status
    expose:
      - "9113"
    depends_on:
      - nginx
    networks:
      - monitornet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    networks:
      - monitornet

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana-storage:/var/lib/grafana
    expose:
      - "3000"
    depends_on:
      - prometheus
    networks:
      - monitornet
      
    
networks:
  webnet:
  monitornet:

volumes:
  grafana-storage: